### PR TITLE
Rearrange navbar

### PR DESCRIPTION
**Pull request by petercoyne**
Rearranged the nav bar a bit. Let me know what ye think!

image

### CODE REVIEW

**Comment by DavidFitzharris** [comment]
hadnt seen this so apologies on late reply! Looks cool! take it the top left icon is gona be the QA? might be good t standardise the link logo up top across all the pages when we come to it , I like the one ya have there that underlines on hover

**Comment by petercoyne** [comment]
No worries on late reply :) I was mostly just trying to get a feel for how pull requests work really. The top left would be the quick access, yeah. Top right would be a link to the about page, logo is a link to home page. I can add the top logo to both pages if we're happy to go ahead with it.

**Comment by DavidFitzharris** [comment]
Yeah im still getting the head round it myself. Can chat about it one the meetings! Nice one with that though, leading the way with it anyway

**Comment by petercoyne** [comment]
Moved stuff around again, think it's a bit stronger visually this way.

image

**Pull request merged**
